"""added listorder column in DictRelationStatus table

Revision ID: 0a20e524bb16
Revises: 1ce3098f7e8a
Create Date: 2024-03-11 15:28:45.222410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a20e524bb16'
down_revision = '1ce3098f7e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_dict_relation_status')
    with op.batch_alter_table('dict_relation_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listorder', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.alter_column('relation_status_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.alter_column('relation_status_id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('dict_relation_status', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('listorder')

    op.create_table('_alembic_tmp_dict_relation_status',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('listorder', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
