"""dictionaries tables added

Revision ID: 0e510964ea40
Revises: 183a398fe5fe
Create Date: 2024-02-11 21:56:43.415034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e510964ea40'
down_revision = '183a398fe5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('dict_employer_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('dict_employment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.drop_table('area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hh_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.drop_table('dict_employment')
    op.drop_table('dict_employer_type')
    op.drop_table('dict_area')
    # ### end Alembic commands ###
