"""vacancy_relation table

Revision ID: 139f48da0645
Revises: 919f789c4ca0
Create Date: 2024-02-11 14:07:57.538812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139f48da0645'
down_revision = '919f789c4ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.alter_column('relations',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.alter_column('relations',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
