"""area dict added

Revision ID: 183a398fe5fe
Revises: 9b053768ce88
Create Date: 2024-02-11 21:31:35.401996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183a398fe5fe'
down_revision = '9b053768ce88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hh_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area')
    # ### end Alembic commands ###
