"""hh_relations column in VacancyRelation added

Revision ID: 1ce3098f7e8a
Revises: c1a24d47bd6e
Create Date: 2024-03-04 14:49:43.525136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3098f7e8a'
down_revision = 'c1a24d47bd6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hh_relations', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.drop_column('hh_relations')

    # ### end Alembic commands ###
