"""added dictionaries

Revision ID: 1e7d3486c45f
Revises: 0e510964ea40
Create Date: 2024-02-11 23:08:41.894626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7d3486c45f'
down_revision = '0e510964ea40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dict_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('dict_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    op.create_table('dict_vacancy_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dict_vacancy_type')
    op.drop_table('dict_schedule')
    op.drop_table('dict_experience')
    # ### end Alembic commands ###
