"""description and skills added to vacancy table

Revision ID: 310594c49663
Revises: 152d4c19b5fb
Create Date: 2024-02-14 12:17:39.234016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310594c49663'
down_revision = '152d4c19b5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_skills', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_column('key_skills')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
