"""added "hidden" to users_vacancies table

Revision ID: 6ab066d00ef4
Revises: 6fa9826bbfd6
Create Date: 2024-02-10 15:27:39.567309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab066d00ef4'
down_revision = '6fa9826bbfd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_vacancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_vacancies', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
