"""new fields in user table

Revision ID: b5a082bfa429
Revises: fd47d2fdd5d7
Create Date: 2024-02-02 12:58:05.633051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a082bfa429'
down_revision = 'fd47d2fdd5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=64), nullable=True))
        batch_op.alter_column('registration_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index('ix_user_registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_registration_date', ['registration_date'], unique=False)
        batch_op.alter_column('registration_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
