"""employer table and relation with vacancy added

Revision ID: b84d37ef6bce
Revises: b0057c87f77b
Create Date: 2024-02-14 15:05:02.470890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84d37ef6bce'
down_revision = 'b0057c87f77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('site_url', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('industries', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('alternate_url', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_employer_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employer_type_id'), ['type_id'], unique=False)
        batch_op.create_foreign_key('fk_employer_type_id', 'dict_employer_type', ['type_id'], ['id'])
        batch_op.create_foreign_key('fk_employer_area_id', 'dict_area', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employer_area_id', type_='foreignkey')
        batch_op.drop_constraint('fk_employer_type_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employer_type_id'))
        batch_op.drop_index(batch_op.f('ix_employer_area_id'))
        batch_op.drop_column('alternate_url')
        batch_op.drop_column('industries')
        batch_op.drop_column('area_id')
        batch_op.drop_column('type_id')
        batch_op.drop_column('site_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
