"""changed VacancyRelation column, added DictRelationStatus

Revision ID: c1a24d47bd6e
Revises: b84d37ef6bce
Create Date: 2024-03-03 23:13:43.966779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a24d47bd6e'
down_revision = 'b84d37ef6bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_vacancy')
    with op.batch_alter_table('dict_relation_status', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('relation_status_id', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_relation_status_id', 'dict_relation_status', ['relation_status_id'], ['id'])
        batch_op.drop_column('notes')
        batch_op.drop_column('relations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacancy_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relations', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_relation_status_id', type_='foreignkey')
        batch_op.drop_column('relation_status_id')
        batch_op.drop_column('favorite')

    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.alter_column('snippet',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('dict_relation_status', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_vacancy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hh_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('alternate_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('published_at', sa.DATETIME(), nullable=True),
    sa.Column('employer_id', sa.INTEGER(), nullable=True),
    sa.Column('archived', sa.BOOLEAN(), nullable=True),
    sa.Column('salary', sa.VARCHAR(length=128), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('contacts', sa.VARCHAR(), nullable=True),
    sa.Column('initial_created_at', sa.DATETIME(), nullable=True),
    sa.Column('area_id', sa.INTEGER(), nullable=True),
    sa.Column('employment_id', sa.INTEGER(), nullable=True),
    sa.Column('experience_id', sa.INTEGER(), nullable=True),
    sa.Column('schedule_id', sa.INTEGER(), nullable=True),
    sa.Column('type_id', sa.INTEGER(), nullable=True),
    sa.Column('snippet', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('key_skills', sa.VARCHAR(), nullable=True),
    sa.Column('professional_roles', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['dict_area.id'], name='fk_vacancy_area_id'),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], name='fk_vacancy_employer_id'),
    sa.ForeignKeyConstraint(['employment_id'], ['dict_employment.id'], name='fk_vacancy_employment_id'),
    sa.ForeignKeyConstraint(['experience_id'], ['dict_experience.id'], name='fk_vacancy_experience_id'),
    sa.ForeignKeyConstraint(['schedule_id'], ['dict_schedule.id'], name='fk_vacancy_schedule_id'),
    sa.ForeignKeyConstraint(['type_id'], ['dict_vacancy_type.id'], name='fk_vacancy_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hh_id')
    )
    # ### end Alembic commands ###
